### ISSUE TITLE
Create a search results dropdown

### ISSUE THREAD

**Issue by chorn99** [willinteractive/will-style#47]
@chadmoone : Can you add inspiration here?

**Comment by dillonlucente** [comment]
@chorn99 do you remember what this is about? Can we open a new issue related to it with some more specifics?

**Comment by chorn99** [comment]
Chad wanted an auto-populating as-you-type dropdown of search results. I haven't seen the need for this yet. Maybe for the main site. But I think we can safely close this issue.
