### ISSUE TITLE
Add Respond.js and Rem.js to asset pipeline

### ISSUE THREAD

**Issue by chorn99** [willinteractive/will-style#52]
```html
<!--[if lte IE 8]>
  <%= javascript_include_tag "respond.min.js" %>
  <%= javascript_include_tag "rem.min.js" %>
<![endif]-->
```

https://github.com/RouL/respond-js-rails

**Comment by dillonlucente** [comment]
I don't think there's any harm in including them in all-styles, as they won't break newer browsers and they're not large scripts. I added a responsive script that we can include for IE8 support.
