### ISSUE TITLE
Work around IE9 4096 per-file Tag Limit

### ISSUE THREAD

**Issue by dillonlucente** [willinteractive/will-style#54]
You learn something new every day. It turns out real IE9 and below (not emulated) has a per-file limit of 4096 declarations. Everything after that is ignored. Our old styles for the testbed went well beyond this limit and I'm sure that the new apps will as well.

If we want to support IE9 and below for our web apps, we need to figure out a way to serve split css files. I hacked this manually for the Testbed for now, but it's going to be a pain to automate.

We can use these as inspiration:

https://gist.github.com/ChristianPeters/2398394#file_lib_css_splitter.rb

https://github.com/zweilove/css_splitter

**Comment by chorn99** [comment]
I think this is where public vs private stylesheets really are important.
For internal (WILLie) use, I don’t care to support IE9, but for public we
should. Public stylesheets should have minimal styles.​

**Comment by dillonlucente** [comment]
Yeah, let me put a public stylesheet in this and see how close we get.

http://snippet.bevey.com/css/selectorCount.php

**Comment by dillonlucente** [comment]
We'll still need to trim down the public sheets, Access public.css has 4657 selectors.

**Comment by chorn99** [comment]
Ugh, yeah I guess this is where using a framework can bite you in the a**​

**Comment by dillonlucente** [comment]
This should work:

https://github.com/zweilove/css_splitter

**Comment by dillonlucente** [comment]
Instructions are up. Looks pretty simple.
